# Generated by Django 5.0.3 on 2024-04-02 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('full_name', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('age', models.IntegerField()),
            ],
        ),
    ]
